# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: passport_postgres
    environment:
      POSTGRES_USER: passport_user
      POSTGRES_PASSWORD: super_password_123
      POSTGRES_DB: passport_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes: 
  pgdata: